export const CHANGE_SONG_DETAIL = "player/CHANGE_SONG_DETAIL"
export const CHANGE_LYRIC = "play/CHANGE_LYRIC"
export const CHANGE_LYRIC_INDEX = 'play/CHANGE_LYRIC_INDEX'
export const CHANGE_SIMI_PLAY_LIST = "play/CHANGE_SIMI_PLAY_LIST"
export const CHANGR_SIMI_SONG = "paly/CHANGR_SIMI_SONG"
export const CHANGE_PLAY_LIST  = 'play/CHANGE_PLAY_LIST'
export const CHANGE_CURRENTINDEX = 'play/CHANGE_CURRENTINDEX'
export const CHANGE_SEQUENCE = 'play/CHANGE_SEQUENCE'
