export const CHANGE_DJRDIO_CATEGORY = 'djrdio/CHANGE_DJRDIO_CATEGORY';
export const CHANGE_CURRENT_ID = 'djrdio/CHANGE_CURRENT_ID';
export const CHANGE_DJRDIO_RECOMMEND = 'djrdio/CHANGE_DJRDIO_RECOMMEND';
export const CHANGE_DJRADIO_RADIOS = 'djrdio/CHANGE_DJRADIO_RADIOS';
