export const CHANGE_CATEGORY = "SONG/CHANGE_CATEGORY"
export const CHANGE_CURRENT_CATEGORY = "song/CHANGE_CURRENT_CATEGORY"
export const CHANGE_CATEGORY_SONG = 'song/CHANGE_CATEGORY_SONG'

export const PER_PAGE_NUMBER = 35;